;--------------------------------------------------
; Meta Section
;--------------------------------------------------
[Meta]
TerminalPath = C:\Program Files\Dukascopy MetaTrader 5\terminal64.exe
DataFolderPath = C:\Users\zarif\AppData\Roaming\MetaQuotes\Terminal\3CA1B4AB7DFED5C81B1C7F1007926D06

;--------------------------------------------------
; Account Section
;--------------------------------------------------
[Account]
Server = Dukascopy-demo-mt5-1
Login = 561267838
Password = dwaB2`uv
