;--------------------------------------------------
; Meta Section
;--------------------------------------------------
[Meta]
TerminalPath = C:\Program Files\Dukascopy MetaTrader 5\terminal64.exe
DataFolderPath = C:\Users\zarif\AppData\Roaming\MetaQuotes\Terminal\3CA1B4AB7DFED5C81B1C7F1007926D06

;--------------------------------------------------
; Account Section
;--------------------------------------------------
[Account]
Server = Dukascopy-demo-mt5-1
Login = 561267838
Password = dwaB2`uv


;--------------------------------------------------
; Tester Section
;--------------------------------------------------
[Tester]
; Path is relative to MQL5\Experts folder unless otherwise specified.
Expert = Lookback StrategyTradeTest-Rev401 inTrend-v1.0.20.ex5

; The symbol (pair) on which you want to run the test/optimization.
Symbol = USDJPY-CUSTOM

; The timeframe (period) on which to run the test (e.g., M1, M5, M15, M30, H1, H4, D1, etc.)
Period = M15

; Start date for testing (format: yyyy.mm.dd).
FromDate = 2008.01.01

; End date for testing (format: yyyy.mm.dd).
ToDate = 2024.12.31

; Initial deposit in the strategy tester.
Deposit = 100000

; Optimization mode:
; 1 = Slow, complete optimization
; 2 = Fast genetic-based optimization
; 3 = All symbols selected in Market Watch
; 4 = All symbols in the tester's symbol list
Optimization = 1

; Optimization criterion:
;  0 = Maximize balance
;  1 = Maximize profit factor
;  2 = Maximize expected payoff
;  3 = Minimize drawdown
OptimizationCriterion = 0,

;--------------------------------------------------
; Tester Inputs Section => Tester Value || Start Value || Step Value || Stop Value || Y or N -> UseForOptimize
;--------------------------------------------------
[TesterInputs]
_Inp_Control_Mode=0||0||0||1||N
_Inp_TestYears=2014,2018,2023,2024
_Inp_RiskAmount=2000.0||2000.0||200.000000||20000.000000||N
_Inp_TradeTimeFrame=15||0||0||49153||N
_ExpertRun_onTesterTF_true_is_FastRuningMode=true||false||0||true||N
_Inp_RewardToRisk=4||2.0||0.200000||20.000000||N
_SL_ATR_Multiply=2||1.5||0.150000||15.000000||N
_Period_Start=28||14||1||140||N
_ChangePeriod_ofSignal=false||false||0||true||N
_Divid=4||3.0||0.300000||30.000000||N
_TrixLimitCal_Maxcand=3000||3000||1||30000||N
_Changover_MaxCan_Passed=10||10||1||100||N
_Trend_HighestLowestCan_MaxCanNum=75||10||1||100||N
_Fix_changover_candle=false||false||0||true||N
; Modify SL
_Inp_RiskFree=false||false||0||true||N
_Inp_Tp_Percent_For_RiskFree=20||65.0||6.500000||650.000000||N
_Inp_SL_Modify_Percent=70||25.0||2.500000||250.000000||N
; Spread Modify SL
_ModifyBuyLimit_Order_BasedOnMaxSpread=true||false||0||true||N
_ModifySell_Pos_BasedOnMaxSpread=true||false||0||true||N
_isWriteModifySLBySPfile=true||false||0||true||N
_ModifyBuyLimitSL_Mode=0||0||0||1||N
_ModifySell_SLMode=0||0||0||1||N
_XminutePreForStartCheckTime=5||5||1||50||N
; Account Margin
_isWriteAccountMargin=false||false||0||true||N
; Upcoming News
_Inp_disableCheckUpcoming=true||false||0||true||N
_Inp_ThirdCondition=false||false||0||true||N
_Inp_enableInterestRateNews=false||false||0||true||N
_Inp_NewsCheckPeriod_minutes=30||30||1||300||N
_Inp_UseGMTnews=false||false||0||true||N
_Inp_ClosingOrdersMethod=0||0||0||3||N
_Inp_NewsCheckPeriodOpen_minutes=60||60||1||600||N
_Inp_isHighPriorityNews=false||false||0||true||N
; Sell Position TP Touch
_IsCheckSellPositionTPtouch=false||false||0||true||N
; Close End Of Day & Week
_Inp_closeEndOfDay=false||false||0||true||N
_Inp_closeEndOfWeek=false||false||0||true||N
_Inp_closeEndOfDaySoonerMinutes=0||0||1||10||N
; Close After X Days
_Inp_maximumTradeDuration=1||24||24||156||Y
_Inp_maximumDistanceBetweenOpenOrder=360||1||1||10||N
; Gap Control
_Inp_enableGapControl=false||false||0||true||N
_Inp_checkEndOfYear=true||false||0||true||N
; File Arguments
InpUseFileArguments=false||false||0||true||N
InpFileArgumentCSVName=
InpFileArgsCount=0||0||1||10||N
; Draw & Printing
_drawTrendDirections=false||false||0||true||N
_distanceOfTrendFromCandleInPoint=100||100||1||1000||N
_disableShowingIndicatorsOnTestingChart=false||false||0||true||N
_trendDownColor=255
_trendUpColor=32768
doPrint=false||false||0||true||N
; Controlling Flags
_inpCheckOrderExistance=false||false||0||true||N
_inpCheckSameDirection=false||false||0||true||N
_customSymbolPrefix=-CUSTOM
inpDoPrintModifies=false||false||0||true||N